export type T_ITunesMusicTrackApiRes = {
    wrapperType: 'track';
    kind: 'song';
    artistId: number;
    collectionId?: number;
    trackId: number;
    artistName: string;
    collectionName?: string;
    trackName: string;
    collectionCensoredName?: string;
    trackCensoredName: string;
    artistViewUrl: string;
    collectionViewUrl?: string;
    trackViewUrl: string;
    previewUrl?: string;
    artworkUrl30?: string;
    artworkUrl60?: string;
    artworkUrl100?: string;
    collectionPrice?: number;
    trackPrice?: number;
    releaseDate: Date;
    collectionExplicitness: string;
    trackExplicitness: string;
    discCount?: number;
    discNumber?: number;
    trackCount?: number;
    trackNumber?: number;
    trackTimeMillis?: number;
    country: string;
    currency: string;
    primaryGenreName: string;
    isStreamable?: boolean;
};

export type T_ITunesMusicTrack = {
    id: string;
    title: string;
    artist: string;
    album: string;
    albumId?: string;
    artistId: string;
    releaseDate: string;
    year: number;
    genre: string;
    track: number;
    disc: number;
    duration_ms: number;
    artwork?: string;
};

export type T_ITunesCollection = {
    wrapperType: 'collection';
    collectionType: 'Album';
    artistId: number;
    collectionId: number;
    amgArtistId: number;
    artistName: string;
    collectionName: string;
    collectionCensoredName: string;
    artistViewUrl: string;
    collectionViewUrl: string;
    artworkUrl60: string;
    artworkUrl100: string;
    collectionPrice: number;
    collectionExplicitness: 'notExplicit' | 'explicit' | string;
    trackCount: number;
    copyright: string;
    country: string;
    currency: string;
    releaseDate: Date;
    primaryGenreName: string;
};
