import APP_ROUTES from '@/constants/routes/app.routes';

export const AUTH_ROUTES: string[] = [APP_ROUTES.AUTH.LOGIN, APP_ROUTES.AUTH.REGISTER, APP_ROUTES.AUTH.FORGOT_PASSWORD, APP_ROUTES.AUTH.ERROR];

export const DEFAULT_AUTH_ROUTE = APP_ROUTES.AUTH.LOGIN;
export const DEFAULT_AUTH_REDIRECT = APP_ROUTES.ROOT;
